project:
  type: website
  output-dir: docs

website:
  title: "Marcelo Ortiz M."
  google-analytics: 
    tracking-id: "G-D6PKRHR4EN"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: about.qmd
        text: About
format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    page-layout: full

editor: visual

