project:
  type: website
  output-dir: docs

website:
  title: "Marcelo Ortiz"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Teaching

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    page-layout: full

editor: visual

