---
title: "Research"
---

## Published Articles

-   Peer Financial Reports and Cash Policy (with F. Urzúa).
    -   **European Accounting Review**, 2025.
    -   [Publisher](https://www.tandfonline.com/doi/full/10.1080/09638180.2025.2488344). [Pre-print](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4096239).
    -   Featured by [BSE Focus](https://focus.bse.eu/how-transparent-reporting-influences-allocation-corporate-cash/) and [ARC Blog](https://eaa-online.org/arc/blog/2025/04/28/forecasting-liquidity-needs-how-peer-financial-reports-help-small-firms-optimize-cash-holdings/).

<!-- -->

-   More than Money: Political Participation by Elite Business Families (with P. Duran and M. Carney).
    -   **Entrepreneurship Theory and Practice**, 2024.
    -   [Publisher](https://journals.sagepub.com/doi/10.1177/10422587241227624). [Pre-print](https://www.researchgate.net/publication/377182500_More_than_money_Political_participation_by_elite_business_families).
    -   Featured by [BSE](https://bse.eu/microupdates/more-money-political-participation-elite-business-families), [Promarket](https://www.promarket.org/2024/03/12/rent-seeking-alone-does-not-explain-why-wealthy-families-run-for-office/), [FamilyBusiness.org](https://familybusiness.org/content/why-prominent-business-families-dive-into-politics) and [Diario Financiero](https://dfmas.df.cl/df-mas/coffee-break/25-de-familias-empresarias-chilenas-han-tenido-incursion-en-politica).
    -   Awarded 2023-24 Schulze Publication Award in the Reseach Insights category (FamilyBusiness.org).

<!-- -->

-   Mandatory Financial Disclosure and the M&A Activity (with F. Urzua, C. Peter, and P. Volpin).
    -   **The Review of Financial Studies**, 2023.
    -   [Publisher](https://academic.oup.com/rfs/article-abstract/36/12/4788/7202058?redirectedFrom=fulltext&login=false). [Pre-print](https://papers.ssrn.com/abstract=3768349). [Internet Appendix](https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/rfs/36/12/10.1093_rfs_hhad052/1/hhad052_supplementary_data.pdf?Expires=1711502290&Signature=Rf6XxFRJiHodfFRqZCI4PW4UHV-6gIkRUAb3fEvVcoJlLPMepM644jkMGfHNblJERi9bvJNJHtcKWqGb28PtNzpPQSTDgtm6GOCMvJe23JWINzbQ36uhixyAw16rLltYnxOs-fQOXmtaw7caGcFeGBF1VDjT7xaBXmNM2Paje5fZcZqJzfuPegPE9-CjC138-F8bUlrN3ngTFeAW7kqA~Oe8G~rqKJ9S3NsSQl5JNyL2I7tddyYFc-3mhu1nN2IF79XUBjckSLYicSxRbyGiAi1kDHg1WIeMUD1~NOKykz-ZwcnlgNST2OO-NB1-W-HZnVmhQcmzJ--q67Ci34G1ow__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA).
    -   Policy Impact: Our findings on the role of transparency thresholds for M&As were incorporated into the discussion of IFRS 3 "Business Combinations" by the [UK Endorsement Board](https://ifrs-springapps-comment-letter-api-1.azuremicroservices.io/v2/download-file?path=638_68180_UK-Endorsement-Board_0_UKEB-Final-Comment-Letter-ED-BCDGI-UNSIGNED.pdf) and analyzed in an [IASB Meeting](https://www.ifrs.org/content/dam/ifrs/meetings/2025/april/iasb/ap18c-pis-evidence-based-feedback.pdf).

<!-- -->

-   Inheritance tax, Shareholder Protection, and the market value of Family Firms (with M. Braun, M. Carney, P. Duran, and J. Riutort).
    -   **Global Strategy Journal**, 2021.
    -   [Publisher](https://onlinelibrary.wiley.com/doi/abs/10.1002/gsj.1394).
    -   Finalist Best Paper Award AIB LAT 2018.

<!-- -->

-   When More Is Better: Multifamily Firms and Firm Performance (with P. Duran).
    -   **Entrepreneurship Theory and Practice**, 2020.
    -   [Publisher](https://journals.sagepub.com/doi/abs/10.1177/1042258719851206?journalCode=etpb).

## Other Publications

-   Inheritance Law.
    -   **Encyclopedia of Family Business**. Book Chapter, 2024.
    -   [Publisher](https://www.elgaronline.com/display/book/9781800888722/ch63.xml). [Pre-print](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4411372).
-   The prevalence of Private Family Firms in Europe.
    -   **White Paper--Family Business and Long-Term Investment Chair**. Dauphine PSL , 2025.
    -   [Publisher](https://dauphine.psl.eu/en/research/chairs-circles-and-research-initiatives/family-businesses-long-term-investment/publications).

## Working Paper

-   The Effect of Mandatory Disclosure on the CEO Market for Private Firms (with Francisco Urzúa and Paolo Volpin).
    -   [Pre-print](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5052279).
    -   R&R at the *Journal of Financial and Quantitative Analysis*.
-   Dynamic Contracting and Corporate Tax Evasion (with Juan Imbet and Vincent Tena).
    -   [Pre-print](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4872375).
-   Private Firms and Offshore Finance: the Real Effects of Data Leaks (with Juan Imbet).
    -   [Pre-print](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4557679).
-   Board Gender Quotas and Female CEOs in Private Firms (with Sonia Falconieri, Francisco Urzúa, and Paolo Volpin).
    -   [Pre-print](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5747103).
    -   Featured by [Forbes CL](https://forbes.cl/mujeres/2025-11-12/estudio-indica-que-cuotas-de-genero-en-directorios-aumentan-la-participacion-de-mujeres-ceo-en-empresas).

## Work in Progress

-   The Impact of Political Nationalism on Corporate Governance (with Caspar Peter).
-   Moral Norms and the Economic Organization of the Firm (with Benito Arruñada and Lucas Lopez).
-   Competitive Executive Compensation with Profitability Shocks (with Gilles Chemla, Juan Imbet, Vincent Tena).